#!/usr/bin/env python3
"""
Cloudflare Network Topology Mapper

Generates an interactive network topology visualization of your
Cloudflare Zero Trust infrastructure.

Usage:
    python main.py [--debug] [--output FILE]

Environment Variables:
    CLOUDFLARE_API_TOKEN: Your Cloudflare API token (required)
    CLOUDFLARE_ACCOUNT_ID: Your Cloudflare account ID (auto-discovered if omitted)
"""

import argparse
import logging
import sys
import webbrowser
from pathlib import Path

__version__ = "0.2.0"

from config import Config
from services.cloudflare_api import CloudflareAPIClient, CloudflareAPIError
from services.network_graph import NetworkGraphBuilder
from services.renderer import TopologyRenderer


def setup_logging(debug: bool = False) -> None:
    """Configure logging."""
    level = logging.DEBUG if debug else logging.INFO
    format_str = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
    logging.basicConfig(
        level=level,
        format=format_str,
        handlers=[
            logging.StreamHandler(sys.stdout),
        ]
    )


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Generate Cloudflare Zero Trust network topology visualization",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Generate topology with default settings
    python main.py

    # Enable debug logging
    python main.py --debug

    # Custom output file
    python main.py --output my_topology.html

    # Skip devices (faster)
    python main.py --no-devices

Environment Variables:
    CLOUDFLARE_API_TOKEN    Cloudflare API token (or use wrangler login)
    CLOUDFLARE_ACCOUNT_ID   Cloudflare account ID (auto-discovered if omitted)
    DEBUG                   Enable debug mode (optional)
        """
    )
    
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging",
    )
    
    parser.add_argument(
        "--output", "-o",
        type=str,
        default="network_topology.html",
        help="Output HTML file path (default: network_topology.html)",
    )
    
    parser.add_argument(
        "--no-browser",
        action="store_true",
        help="Don't open browser after generating",
    )
    
    parser.add_argument(
        "--no-devices",
        action="store_true",
        help="Skip fetching WARP devices (faster)",
    )
    
    parser.add_argument(
        "--no-tunnel-configs",
        action="store_true",
        help="Skip fetching detailed tunnel configurations",
    )
    
    parser.add_argument(
        "--include-gateway",
        action="store_true",
        help="Include Gateway firewall rules",
    )

    parser.add_argument(
        "--demo",
        action="store_true",
        help="Use synthetic demo data (no Cloudflare API calls). Safe for public deploys.",
    )

    parser.add_argument(
        "--setup",
        action="store_true",
        help="Interactive first-run setup: writes a .env file with your Cloudflare token.",
    )

    return parser.parse_args()


def run_setup() -> int:
    """Interactive setup that writes a .env file for the user."""
    from pathlib import Path

    print("\n🌐 Cloudflare Topology — setup")
    print("=" * 50)
    print("This will create a .env file so `python main.py` just works.\n")

    env_path = Path(".env")
    if env_path.exists():
        resp = input(f".env already exists at {env_path.absolute()}. Overwrite? [y/N] ").strip().lower()
        if resp != "y":
            print("Aborted. Your existing .env was not touched.")
            return 0

    print("\nCreate a token (opens in browser): https://dash.cloudflare.com/profile/api-tokens")
    print("  Permissions needed: 'Account → Zero Trust: Read' + 'Account → Access: Apps and Policies: Read'\n")

    try:
        import webbrowser
        if input("Open the API tokens page in your browser now? [Y/n] ").strip().lower() not in ("n", "no"):
            webbrowser.open("https://dash.cloudflare.com/profile/api-tokens")
    except Exception:
        pass

    token = input("\nPaste your CLOUDFLARE_API_TOKEN: ").strip()
    if not token:
        print("❌ No token provided. Aborted.")
        return 1

    account = input("CLOUDFLARE_ACCOUNT_ID (leave blank to auto-discover): ").strip()

    lines = [
        "# Cloudflare Topology — generated by `python main.py --setup`",
        f"CLOUDFLARE_API_TOKEN={token}",
    ]
    if account:
        lines.append(f"CLOUDFLARE_ACCOUNT_ID={account}")
    env_path.write_text("\n".join(lines) + "\n")
    try:
        env_path.chmod(0o600)
    except OSError:
        pass

    print(f"\n✅ Wrote {env_path.absolute()} (chmod 600)")
    print("Next:  python main.py")
    return 0


def main() -> int:
    """Main entry point."""
    args = parse_args()

    if args.setup:
        return run_setup()

    # Setup logging
    setup_logging(args.debug)
    logger = logging.getLogger(__name__)
    
    logger.info("🌐 Cloudflare Network Topology Mapper")
    logger.info("=" * 50)
    
    try:
        if args.demo:
            from services.demo_data import build_demo_topology

            logger.info("🎭 Demo mode — using synthetic data (no Cloudflare API calls)")
            config = Config(api_token="demo", account_id="demo-account")
            config.debug = args.debug
            config.output_file = args.output
            topology = build_demo_topology()
        else:
            # Load configuration from environment
            config = Config.from_env()
            config.debug = args.debug
            config.output_file = args.output

            # Initialize API client (auto-discovers account ID if needed)
            api_client = CloudflareAPIClient(config)

            logger.info(f"Account ID: {config.account_id}")

            # Fetch topology data
            logger.info("📡 Fetching topology data from Cloudflare API...")
            topology = api_client.fetch_topology(
                include_tunnel_configs=not args.no_tunnel_configs,
                include_app_policies=True,
                include_devices=not args.no_devices,
                include_gateway_rules=args.include_gateway,
            )
        
        # Print summary
        logger.info("")
        logger.info("📊 Resources Found:")
        logger.info(f"   Tunnels:           {len(topology.tunnels)}")
        logger.info(f"   Applications:      {len(topology.applications)}")
        logger.info(f"   Policies:          {len(topology.policies)}")
        logger.info(f"   Groups:            {len(topology.groups)}")
        logger.info(f"   Identity Providers: {len(topology.identity_providers)}")
        logger.info(f"   Virtual Networks:  {len(topology.virtual_networks)}")
        logger.info(f"   Routes:            {len(topology.routes)}")
        logger.info(f"   Devices:           {len(topology.devices)}")
        if args.include_gateway:
            logger.info(f"   Gateway Rules:     {len(topology.gateway_rules)}")
        logger.info("")
        
        # Build network graph
        logger.info("🔧 Building network graph...")
        graph_builder = NetworkGraphBuilder()
        graph_builder.build(topology)
        
        # Calculate node counts for UI
        node_counts = {
            'tunnel': len(topology.tunnels),
            'application': len(topology.applications),
            'policy': len(topology.policies),
            'group': len(topology.groups),
            'identity_provider': len(topology.identity_providers),
            'virtual_network': len(topology.virtual_networks),
            'route': len(topology.routes),
            'device': len(topology.devices),
        }
        
        # Render to HTML
        logger.info("🎨 Rendering visualization...")
        renderer = TopologyRenderer(config)
        output_path = renderer.render(graph_builder, args.output, node_counts)
        
        # Success message
        output_abs = Path(output_path).absolute()
        logger.info("")
        logger.info("✅ Topology generated successfully!")
        logger.info(f"   Output: {output_abs}")
        logger.info(f"   Nodes:  {len(graph_builder.nodes)}")
        logger.info(f"   Edges:  {len(graph_builder.edges)}")
        
        # Open in browser
        if not args.no_browser:
            logger.info("")
            logger.info("🌍 Opening in browser...")
            webbrowser.open(f"file://{output_abs}")
        
        return 0
        
    except ValueError as e:
        logger.error(f"❌ Configuration error: {e}")
        return 1
        
    except CloudflareAPIError as e:
        logger.error(f"❌ Cloudflare API error: {e}")
        if e.errors:
            for error in e.errors:
                logger.error(f"   - {error.get('message', 'Unknown error')}")
        return 2
        
    except Exception as e:
        logger.exception(f"❌ Unexpected error: {e}")
        return 3


if __name__ == "__main__":
    sys.exit(main())
